import { Difficulty, ValidatedVocabularyItem } from './types';

export const DEFAULT_VOCABULARY: ValidatedVocabularyItem[] = [
  {
    word: 'benevolent',
    definition: 'Well meaning and kindly; wishing to do good to others',
    exampleSentence: 'The benevolent neighbor brought warm soup to the elderly couple during the blizzard.',
    difficulty: Difficulty.EASY,
  },
  {
    word: 'candid',
    definition: 'Truthful and straightforward; frank in speech or expression',
    exampleSentence: "She gave a candid assessment of the project's chances of success.",
    difficulty: Difficulty.EASY,
  },
  {
    word: 'diligent',
    definition: 'Having or showing care and conscientious effort in one\'s work',
    exampleSentence: 'The diligent student spent hours researching primary sources for her thesis.',
    difficulty: Difficulty.EASY,
  },
  {
    word: 'frugal',
    definition: 'Sparing or economical with regard to money or resources',
    exampleSentence: 'By living a frugal lifestyle he managed to save enough money to buy his first home.',
    difficulty: Difficulty.EASY,
  },
  {
    word: 'lucid',
    definition: 'Expressed clearly and easy to understand',
    exampleSentence: 'The professor gave a lucid explanation of a complex quantum mechanics concept.',
    difficulty: Difficulty.EASY,
  },
  {
    word: 'resilient',
    definition: 'Able to withstand or recover quickly from difficult conditions',
    exampleSentence: 'The community proved resilient after rebuilding the town following the storm.',
    difficulty: Difficulty.EASY,
  },
  {
    word: 'serene',
    definition: 'Calm peaceful and untroubled; tranquil',
    exampleSentence: 'The surface of the mountain lake was completely serene at sunrise.',
    difficulty: Difficulty.EASY,
  },
  {
    word: 'tactile',
    definition: 'Connected with the sense of touch or perceived through touching',
    exampleSentence: 'Children often learn best through tactile experiences like sculpting clay.',
    difficulty: Difficulty.EASY,
  },
  {
    word: 'wary',
    definition: 'Feeling or showing caution about possible dangers or problems',
    exampleSentence: 'The hiker grew wary of rustling sounds in the dense bushes ahead.',
    difficulty: Difficulty.EASY,
  },
  {
    word: 'zeal',
    definition: 'Great energy or enthusiasm in pursuit of a cause or objective',
    exampleSentence: 'She tackled the charity campaign with contagious zeal and determination.',
    difficulty: Difficulty.EASY,
  },
  {
    word: 'ambiguous',
    definition: 'Open to more than one interpretation; having a double meaning',
    exampleSentence: 'The politician gave an ambiguous reply when asked about future tax increases.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'articulate',
    definition: 'Expressing thoughts and ideas clearly and effectively in speech or writing',
    exampleSentence: 'He was exceptionally articulate when defending his research findings to the board.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'austere',
    definition: 'Severe or strict in manner or appearance; without luxuries or comforts',
    exampleSentence: 'The monks lived an austere life devoted entirely to study and contemplation.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'bolster',
    definition: 'Support or strengthen; prop up something weak',
    exampleSentence: 'The new evidence served to bolster the defense attorney\'s closing argument.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'ephemeral',
    definition: 'Lasting for a very short time; fleeting or transient',
    exampleSentence: 'The cherry blossoms offer an ephemeral beauty that disappears after a brief spring shower.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'meticulous',
    definition: 'Showing great attention to detail; very careful and precise',
    exampleSentence: 'The watchmaker was meticulous in placing each microscopic gear into the timepiece.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'pragmatic',
    definition: 'Dealing with things sensibly and realistically based on practical considerations',
    exampleSentence: 'Instead of debating ideal scenarios they chose a pragmatic solution that solved the immediate bottleneck.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'supercilious',
    definition: 'Behaving or looking as though one thinks one is superior to others; arrogant',
    exampleSentence: 'The critic cast a supercilious glance at the amateur painter\'s display.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'ubiquitous',
    definition: 'Present appearing or found everywhere at the same time',
    exampleSentence: 'Smartphones have become ubiquitous in almost every part of modern life.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'venerate',
    definition: 'Regard with great respect; hold in profound esteem or reverence',
    exampleSentence: 'In many cultures younger generations venerate their elders for their life wisdom.',
    difficulty: Difficulty.MEDIUM,
  },
  {
    word: 'acquiesce',
    definition: 'Accept something reluctantly but without protest; submit passively',
    exampleSentence: 'Exhausted after hours of negotiation the union leaders finally acquiesced to the compromise terms.',
    difficulty: Difficulty.HARD,
  },
  {
    word: 'bellicose',
    definition: 'Demonstrating aggression and willingness to fight; hostile or warlike',
    exampleSentence: 'The ambassador condemned the nation\'s bellicose rhetoric as a threat to regional peace.',
    difficulty: Difficulty.HARD,
  },
  {
    word: 'capricious',
    definition: 'Given to sudden and unaccountable changes of mood or behavior; erratic',
    exampleSentence: 'The capricious mountain weather shifted from blazing sunshine to hailstorms within thirty minutes.',
    difficulty: Difficulty.HARD,
  },
  {
    word: 'deleterious',
    definition: 'Causing harm or damage often in a subtle or unexpected way',
    exampleSentence: 'Regular lack of sleep can have deleterious effects on long-term cognitive function.',
    difficulty: Difficulty.HARD,
  },
  {
    word: 'enervate',
    definition: 'Cause someone to feel drained of energy or vitality; weaken',
    exampleSentence: 'The sweltering desert heat threatened to enervate the expedition team before noon.',
    difficulty: Difficulty.HARD,
  },
  {
    word: 'fastidious',
    definition: 'Very attentive to and concerned about accuracy detail and cleanliness',
    exampleSentence: 'The head chef was fastidious about the temperature and presentation of every plate leaving the kitchen.',
    difficulty: Difficulty.HARD,
  },
  {
    word: 'gregarious',
    definition: 'Fond of company; sociable and outgoing',
    exampleSentence: 'Being inherently gregarious he quickly made lifelong friends wherever he traveled.',
    difficulty: Difficulty.HARD,
  },
  {
    word: 'loquacious',
    definition: 'Tending to talk a great deal; talkative',
    exampleSentence: 'The loquacious tour guide shared endless fascinating anecdotes throughout the bus ride.',
    difficulty: Difficulty.HARD,
  },
  {
    word: 'obfuscate',
    definition: 'Deliberately make something obscure unclear or difficult to understand',
    exampleSentence: 'The spokesperson attempted to obfuscate the financial discrepancies by using convoluted jargon.',
    difficulty: Difficulty.HARD,
  },
  {
    word: 'sagacious',
    definition: 'Having or showing keen mental discernment good judgment and wisdom',
    exampleSentence: 'The elder was revered for her sagacious counsel during times of tribal conflict.',
    difficulty: Difficulty.HARD,
  },
];
